name: ScriptActions

on:
  push:
    branches:  
      - master
      - workb

env:
  CONTENTFUL_SPACE_ID: ${{ secrets.CONTENTFUL_SPACE_ID }}
  CONTENTFUL_ACCESS_TOKEN: ${{ secrets.CONTENTFUL_ACCESS_TOKEN }}
  MAILCHIMP_ENDPOINT: ${{ secrets.MAILCHIMP_ENDPOINT }}    
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  CDK_DEFAULT_ACCOUNT : ${{ secrets.CDK_DEFAULT_ACCOUNT }}
  CDK_DEFAULT_REGION: 'eu-west-3'

jobs:
  build-job:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      name: 'setup node'
      with:
        node-version: '16'

    - name: 'build site'
      run : |
        npm i
        npm run build
      
    - name: 'Deploy site'
      working-directory: ./aws-iac
      run : |
        npm i npm
        npm run build
        npm i cdk
        cdk deploy 
