name: ScriptActions

on:
  push:
    branches:  master 

env:
  CONTENTFUL_SPACE_ID: ${{ secrets.CONTENTFUL_SPACE_ID }}
  CONTENTFUL_ACCESS_TOKEN: ${{ secrets.CONTENTFUL_ACCESS_TOKEN }}
  MAILCHIMP_ENDPOINT: ${{ secrets.MAILCHIMP_ENDPOINT }}    
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

jobs:
  runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      name: 'setup node'
      with:
        node-version: '14'

    - name: 'build site'
      run :  npm i
      run :  npm run build