name: ScriptActions

on:
  push: 
    branches: 
      -master
      -aws-iac

env:
  CONTENTFUL_SPACE_ID: ${{ secrets.CONTENTFUL_SPACE_ID }}
  CONTENTFUL_ACCESS_TOKEN: ${{ secrets.CONTENTFUL_ACCESS_TOKEN }}
  MAILCHIMP_ENDPOINT: ${{ secrets.MAILCHIMP_ENDPOINT }}    
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
  CDK_DEFAULT_ACCOUNT : ${{ secrets.CDK_DEFAULT_ACCOUNT }}
  CDK_DEFAULT_REGION: ${{ secrets.CDK_DEFAULT_REGION }}

jobs:
  build-job:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      name: 'setup node'
      with:
        node-version: '14'

    - name: 'build site'
      run : |
        npm i
        npm run build
      
    - name: 'Deploy site'
      working-directory: ./aws-cdk
      run : |
        npm i npm
        npm run build
        npm i cdk -g
        cdk bootstrap
        cdk deploy 
